# Site settings
title: Events and Threads
tagline: 
email: madhuraparikh@gmail.com  
description: > # this means to ignore newlines until "baseurl"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jdnc.github.io" # the base hostname & protocol for your site
twitter_username: 11011infinity
github_username:  jdnc
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems: [jekyll-paginate]
